# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasicStartUpProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Toast-Swift'#, '~> 4.0.1'
  pod 'MBProgressHUD', '~> 0.9.2' , :inhibit_warnings => true
  # Pods for BasicStartUpProject

end
